stages:
  - build

# 安装依赖
deploy:
  stage: build
  only:
    - develop
    - master
  script:
    - yarn
    - sed -i s/123456//g src/app.module.ts 
    - yarn build
    - rsync  -arc . --exclude node_modules --exclude src  root@100.100.100.100:/home/web/travel
    - ssh root@100.100.100.100 "cd /home/web/travel && yarn && yarn add easy-monitor"
    - ssh root@100.100.100.100 "cd /home/web/travel && pm2 restart travel
"
  tags:
    - build
